services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=https://shorturl.runmydocker-app.com
    networks:
      - tinyurl-network
networks:
  tinyurl-network:
    driver: bridge